#!/bin/bash
php /var/www/loris/project/tools/drop_all_tables.php &&
cat /var/www/loris/project/tables_sql/drop_all_tables_statements.sql | mysql &&
echo "##### SOURCING LORIS SCHEMA #####" >&2 &&
for n in /var/www/loris/SQL/0000-00-*.sql; do echo $n; cat $n | mysql || break; done &&
echo "##### SOURCING INSTRUMENT SCHEMA #####" >&2 &&
for n in /var/www/loris/project/tables_sql/instruments/*.sql; do echo $n; cat $n | mysql || break; done &&
echo "##### SOURCING RAISINBREAD FILES #####" >&2 &&
for n in /var/www/loris/SQL/RB_files/RB_*.sql; do echo $n; cat $n | mysql || break; done &&
echo "##### CUSTOMIZING CONFIGS #####" >&2 &&
cat /var/www/loris/project/tools/cronjob.sql | mysql;
