#!/bin/bash
echo "##### CLEANING INSTRUMENTS DIRECTORY #####" >&2 &&
find /var/www/loris/project/instruments/ -type f -not -name 'README.md' -delete &&
echo "##### CLEARING DATA RELEASE UPLOADS #####" >&2 &&
rm -rf /var/www/loris/modules/data_release/user_uploads/* &&
echo "##### CLEARING DOCUMENT REPOSITORY UPLOADS #####" >&2 &&
rm -rf /var/www/loris/modules/document_repository/user_uploads/* &&
echo "##### CLEARING GENOMICS UPLOADS #####" >&2 &&
rm -rf /data/genomics/* &&
echo "##### CLEARING MRI UPLOADS #####" >&2 &&
rm -rf /data/incoming/* &&
rm -rf /data/imagingData/* &&
echo "##### CLEARING DEFAULT DOWNLOADS #####" >&2 &&
rm -rf /data/download/* &&
echo "##### CLEARING MEDIA UPLOADS #####" >&2 &&
rm -rf /data/mediaUploads/* &&
echo "##### CLEARING INSTRUMENT MANAGER UPLOADS #####" >&2 &&
find /var/www/loris/project/instruments/ -type f -not -name "bmi.linst" -not -name "bmi.readme" -not -name "bmi.rules" -not -name "bmi.score" -not -name "NDB_BVL_Instrument_radiology_review.class.inc" -not -name "NDB_BVL_Instrument_mri_parameter_form.class.inc" -not -name "NDB_BVL_Instrument_medical_history.class.inc" -not -name "NDB_BVL_Instrument_aosi.class.inc" -delete;


